newspaper/urls.py
from django.urls import path

from newspaper.views import (
    index,
    TopicListView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
)


urlpatterns = [
    path("", index, name="index"),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("topics/create/",
         TopicCreateView.as_view(),
         name="topic-create",
    ),
    path("topics/<int:pk>/update/",
         TopicUpdateView.as_view(),
         name="topic-update",
    ),
    path("topics/<int:pk>/delete/",
         TopicDeleteView.as_view(),
         name="topic-delete",
    ),

    path(
        "newspapers/",
        NewspaperListView.as_view(),
        name="newspaper-list",
    ),
    path(
        "newspapers/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail",
    ),
    path("newspapers/create/",
         NewspaperCreateView.as_view(),
         name="newspaper-create",
    ),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),

    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list",
    ),
    path(
        "redactor/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail",
    ),
    path("redactors/create/",
         RedactorCreateView.as_view(),
         name="redactor-create",
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
]

app_name = "newspaper"

newspapers_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls", namespace="newspaper")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/navigation.html
<!-- [ Header ] start -->
  <header class="navbar pcoded-header navbar-expand-lg navbar-light headerpos-fixed header-blue">


        <div class="m-header">
            <a class="mobile-menu" id="mobile-collapse" href="#"><span></span></a>
            <a href="#" class="b-brand">
                <!-- ========   change your logo hear   ============ -->
                <img src="/static/assets/images/newspaper-32.png" alt="" class="logo">&nbsp;&nbsp;Newspaper Agency
                <img src="/static/assets/images/logo-icon.png" alt="" class="logo-thumb">
            </a>
            <a href="#" class="mob-toggler">
                <i class="feather icon-more-vertical"></i>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a href="#" class="pop-search"><i class="feather"></i></a>
                    <div class="search-bar">
                        <input type="text" class="form-control border-0 shadow-none" placeholder="Search here">
                        <button type="button" class="btn-close" aria-label="Close">
                        </button>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li>
                    <div class="dropdown drp-user">
                        <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown">
                            <img src="/static/assets/images/user/avatar-1.jpg" class="img-radius wid-40"
                                alt="User-Profile-Image">
                        </a>
                        <div class="dropdown-menu dropdown-menu-end profile-notification">
                            <div class="pro-head">
                                <img src="/static/assets/images/user/avatar-1.jpg" class="img-radius"
                                    alt="User-Profile-Image">
                                <span>
                                    {{ request.user.username }}
                                </span>
                            </div>
                            <ul class="pro-body">
                                <li>
                                    <a href="{% url 'login' %}"
                                       class="dropdown-item"><i
                                            class="feather icon-lock"></i> Logout</a></li>
                            </ul>
                        </div>
                    </div>
                </li>
            </ul>
        </div>


</header>
<!-- [ Header ] end -->

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
        </li>
      {% endif %}

      <li class="page-item active">
        <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
      </li>

      {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
        </li>
      {% endif %}
    </ul>
{% endif %}

templates/includes/scripts.html
    <script src="/static/assets/js/plugins/popper.min.js"></script>
    <script src="/static/assets/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="/static/assets/js/plugins/bootstrap.min.js"></script>
    <script src="/static/assets/js/pcoded.js"></script>

templates/includes/sidebar.html
 <!-- [ navigation menu ] start -->
  <nav class="pcoded-navbar menupos-fixed menu-light ">
    <div
      class="navbar-wrapper  ">
      <div class="navbar-content scroll-div "
        >
        <ul class="nav pcoded-inner-navbar ">
          <li class="nav-item">
            <a href="/" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span
                class="pcoded-mtext">Home Page</span></a>
          </li>
          <li class="nav-item">
            <a href="{% url 'newspaper:topic-list' %}" class="nav-link "><span class="pcoded-micon"><i
                  class="feather icon-tag"></i></span><span class="pcoded-mtext">Topics</span></a>
          </li>
          <li class="nav-item">
            <a href="{% url 'newspaper:redactor-list' %}" class="nav-link "><span class="pcoded-micon"><i
                  class="feather icon-users"></i></span><span class="pcoded-mtext">Redactors</span></a>
          </li>
          <li class="nav-item"><a href="{% url 'newspaper:newspaper-list' %}" class="nav-link "><span class="pcoded-micon"><i
                  class="feather icon-file-text"></i></span><span class="pcoded-mtext">Newspapers</span></a></li>
        </ul>

        <div class="card text-center">
          <div class="card-body px-3">
            <i class="feather icon-github f-40"></i>
            <h6 class="mt-3">Check repo</h6>
            <a href="https://github.com/Litvinenko23/Litvinenko23-py-newspapers-agency" target="_blank"
              class="btn btn-primary btn-sm text-white m-0">Github Link</a>
          </div>
        </div>

      </div>
    </div>
  </nav>
  <!-- [ navigation menu ] end -->