newspaper/urls.py
from django.urls import path

from newspaper.views import (
    index,
    TopicListView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
)


urlpatterns = [
    path("", index, name="index"),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("topics/create/",
         TopicCreateView.as_view(),
         name="topic-create",
    ),
    path("topics/<int:pk>/update/",
         TopicUpdateView.as_view(),
         name="topic-update",
    ),
    path("topics/<int:pk>/delete/",
         TopicDeleteView.as_view(),
         name="topic-delete",
    ),

    path(
        "newspapers/",
        NewspaperListView.as_view(),
        name="newspaper-list",
    ),
    path(
        "newspapers/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail",
    ),
    path("newspapers/create/",
         NewspaperCreateView.as_view(),
         name="newspaper-create",
    ),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),

    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list",
    ),
    path(
        "redactor/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail",
    ),
    path("redactors/create/",
         RedactorCreateView.as_view(),
         name="redactor-create",
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
]

app_name = "newspaper"

newspapers_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls", namespace="newspaper")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newspaper/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    class Meta:
        ordering = ["username"]
        verbose_name = "redactor"
        verbose_name_plural = "redactors"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("newspaper:redactor-detail", kwargs={"pk": self.pk})


class Newspaper(models.Model):
    title = models.CharField(max_length=255, unique=True)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    publishers = models.ManyToManyField(Redactor, related_name="newspapers")

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return self.title

newspaper/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from newspaper.models import Redactor, Newspaper


class RedactorCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + ("years_of_experience", "first_name", "last_name")


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."})
    )


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title..."})
    )


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username..."})
    )


class RedactorUpdateForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = Redactor
        fields = ["username", "first_name", "last_name"]

newspaper/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from newspaper.forms import RedactorCreationForm, NewspaperForm, NewspaperSearchForm, RedactorSearchForm, \
    TopicSearchForm, RedactorUpdateForm
from newspaper.models import Redactor, Newspaper, Topic


@login_required
def index(request):
    """View function for the home page of the site."""

    num_redactors = Redactor.objects.count()
    num_newspapers = Newspaper.objects.count()
    num_topics = Topic.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_redactors": num_redactors,
        "num_newspapers": num_newspapers,
        "num_topics": num_topics,
        "num_visits": num_visits + 1,
    }

    return render(request, "newspaper/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    template_name = "newspaper/topic_list.html"
    context_object_name = "topic_list"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = TopicSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        queryset = Topic.objects.order_by("name")
        form = TopicSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("newspaper:topic-list")
    template_name = "newspaper/topic_confirm_delete.html"


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")

        context["search_form"] = NewspaperSearchForm(initial={
            "title": title
        })

        return context

    def get_queryset(self):
        queryset = Newspaper.objects.select_related("topic")

        form = NewspaperSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                title__icontains=form.cleaned_data["title"]
            )

        return queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("newspaper:newspaper-list")
    template_name = "newspaper/newspaper_confirm_delete.html"


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = RedactorSearchForm(
            initial={"username": username}
        )

        return context

    def get_queryset(self):
        queryset = Redactor.objects.prefetch_related("newspapers__topic")
        form = RedactorSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )

        return queryset


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    queryset = Redactor.objects.prefetch_related("newspapers__topic")


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorUpdateForm
    success_url = reverse_lazy("newspaper:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("newspaper:redactor-list")
    template_name = "newspaper/redactor_confirm_delete.html"

templates/newspaper/index.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %}

{#<!-- Specific Page CSS goes HERE  -->#}
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <!-- [ Main Content ] start -->
  <div class="pcoded-main-container">
    <div class="pcoded-content">
      <!-- [ breadcrumb ] start -->
      <!-- [ breadcrumb ] end -->
      <!-- [ Main Content ] start -->
      <div class="row">
        <!-- [ sample-page ] start -->
        <div class="col-sm-12">
          <div class="card">

            <div class="card-header">
              <h5>Newspapers Agency Home</h5>
              <div class="card-header-right">
                <div class="btn-group card-option">
                </div>
              </div>
            </div>
            <div class="card-body">
              <p>This is the page of a newspaper agency that has a great team of editors. You have been given the ability to track Redactors assigned to Newspapers.
                                This way you will always know who was the publisher of each newspaper.
              </p>
            </div>
          </div>


                     <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-content">
            <!-- [ Main Content ] start -->
            <div class="row">
                <!-- order-card start -->
                <div class="col-md-6 col-xl-3">
                    <a href="{% url 'newspaper:topic-list' %}">
                    <div class="card bg-c-blue order-card">
                        <div class="card-body">
                            <h6 class="text-white">Topics</h6>
                            <h2 class="text-end text-white"><i class="feather icon-tag float-start"></i><span>{{ num_topics }}</span></h2>
                        </div>
                    </div>
                    </a>
                </div>
                <div class="col-md-6 col-xl-3">
                    <a href="{% url 'newspaper:redactor-list' %}">
                    <div class="card bg-c-green order-card">
                        <div class="card-body">
                            <h6 class="text-white">Redactors</h6>
                            <h2 class="text-end text-white"><i class="feather icon-users float-start"></i><span>{{ num_redactors }}+</span>
                            </h2>
                        </div>
                    </div>
                    </a>
                </div>


                <div class="col-md-6 col-xl-3">
                    <a href="{% url 'newspaper:newspaper-list' %}">
                    <div class="card bg-c-yellow order-card">
                        <div class="card-body">
                            <h6 class="text-white">Newspapers</h6>
                            <h2 class="text-end text-white"><i
                                    class="feather icon-file-text float-start"></i><span>{{ num_newspapers }}+</span></h2>
                        </div>
                    </div>
                    </a>
                </div>
        </div>
        <!-- [ sample-page ] end -->
      </div>
      <!-- [ Main Content ] end -->
    </div>
  </div>

    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

    <!-- Apex Chart -->
    <script src="/static/assets/js/plugins/apexcharts.min.js"></script>

    <!-- custom-chart js -->
    <script src="/static/assets/js/pages/dashboard-main.js"></script>

{% endblock javascripts %}

templates/newspaper/newspaper_confirm_delete.html
{% extends "layouts/base.html" %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">
            <h1 class="card-title">Delete newspaper?</h1>
          </div>
          <div class="card-body">
            <form action="" method="post">
              {% csrf_token %}

              <p>Are you sure you want to delete this newspaper?</p>

              <div class="form-group">
                <div class="btn-group">
                  <input type="submit" value="Yes" class="btn btn-danger">
                  <a href="{% url 'newspaper:newspaper-detail' pk=object.pk %}" class="btn btn-secondary">Cancel</a>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/newspaper/newspaper_detail.html
{% extends "layouts/base.html" %}

{% block content %}

<section class="pcoded-main-container">
  <div class="pcoded-content">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h5>{{ newspaper.title }}</h5>
            <div class="float-right">
              <a href="{% url 'newspaper:newspaper-update' pk=newspaper.id %}" class="btn btn-secondary link-to-page">Update</a>
              <a href="{% url 'newspaper:newspaper-delete' pk=newspaper.id %}" class="btn btn-danger link-to-page">Delete</a>
            </div>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-md-6">
                <p><strong>Topic:</strong> {{ newspaper.topic.name }}</p>
                <p><strong>Publishers:</strong></p>
                <ul>
                  {% for publisher in newspaper.publishers.all %}
                    <li>{{ publisher.first_name }} {{ publisher.last_name }}</li>
                  {% empty %}
                    <li>No publishers found</li>
                  {% endfor %}
                </ul>
              </div>
              <div class="col-md-6">
                <p>{{ newspaper.content }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/newspaper/newspaper_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{{ object|yesno:"Update,Create" }} Newspaper</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="" method="post" novalidate>
          {% csrf_token %}
          {{ form|crispy }}

          <div class="d-flex justify-content-end">
            <input class="btn btn-primary" type="submit" value="Submit">
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/newspaper/newspaper_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}


{% block content %}
<section class="pcoded-main-container">
    <div class="pcoded-content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Newspaper List</h5>
                          <form action="" method="get" class="form-inline">
                            {{ search_form|crispy }}
                              <input  id="id_id_title" class="btn btn-secondary" type="submit" value="🔎">
                          </form>
                        <a style="float: right" href="{% url 'newspaper:newspaper-create' %}" class="btn btn-primary link-to-page">Create</a>
                    </div>
                    <div class="card-body table-border-style">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Title</th>
                                        <th>Topic</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if newspaper_list %}
                                    {% for newspaper in newspaper_list %}
                                    <tr>
                                        <td><a href="{% url "newspaper:newspaper-detail" pk=newspaper.id %}">{{ newspaper.id }}</a></td>
                                        <td>{{ newspaper.title }}</td>
                                        <td>{{ newspaper.topic.name }}</td>
                                    </tr>
                                    {% endfor %}
                                    {% else %}
                                    <tr>
                                        <td colspan="3">There are no newspapers in newspapers agency</td>
                                    </tr>
                                    {% endif %}
                                </tbody>
                                {% block pagination %}
                                    {% include 'includes/pagination.html' %}
                                {% endblock %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}


<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/newspaper/redactor_confirm_delete.html
{% extends "layouts/base.html" %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <h1>Delete redactor?</h1>
        <form action="" method="post">
          {% csrf_token %}
          <input type="submit" value="Yes" class="btn btn-danger">
          <a href="{% url 'newspaper:redactor-list' %}" class="btn btn-secondary">Cancel</a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/newspaper/redactor_detail.html
{% extends "layouts/base.html" %}
{% block content %}

<section class="pcoded-main-container">
  <div class="pcoded-content">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h5>Redactor Details</h5>
          </div>
          <div class="card-body">
            <h6>Username: {{ redactor.username }}</h6>
            <div class="d-flex justify-content-between align-items-center">
              <a href="{% url 'newspaper:redactor-delete' pk=redactor.id %}" class="btn btn-danger link-to-page">Delete</a>
              <a href="{% url 'newspaper:redactor-update' pk=redactor.id %}" class="btn btn-secondary link-to-page">Update</a>
            </div>
            <hr>
            <p><strong>First name:</strong> {{ redactor.first_name }}</p>
            <p><strong>Last name:</strong> {{ redactor.last_name }}</p>
            <p><strong>Years of experience:</strong> {{ redactor.years_of_experience }}</p>
            <p><strong>Is staff:</strong> {{ redactor.is_staff }}</p>
                  <div class="ml-3">
              <h4>Newspapers</h4>

              {% for newspaper in redactor.newspapers.all %}
              <hr>
              <p><strong>Title:</strong> {{ newspaper.title }}</p>
              <p><strong>Topic:</strong> {{ newspaper.topic.name }}</p>
              <p class="text-muted"><strong>Id:</strong> {{newspaper.id}}</p>

              {% empty %}
              <p>No newspapers!</p>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
   </div>
</section>
{% endblock %}
<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/newspaper/redactor_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{{ object|yesno:"Update,Create" }} Redactor</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="" method="post" novalidate>
          {% csrf_token %}
          {{ form|crispy }}

          <div class="d-flex justify-content-end">
            <input class="btn btn-primary" type="submit" value="Submit">
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/newspaper/redactor_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% block content %}
<section class="pcoded-main-container">
  <div class="pcoded-content">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h5>Redactor List</h5>
              <form action="" method="get" class="form-inline">
                  {{ search_form|crispy }}
                  <input class="btn btn-secondary" type="submit" value="🔎">
              </form>
            <a style="float: right" href="{% url 'newspaper:redactor-create' %}" class="btn btn-primary link-to-page">Create</a>
          </div>
          <div class="card-body table-border-style">
            <div class="table-responsive">
            <div class="table-responsive w-100">
              <table class="table table-width-100">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Username</th>
                    <th>First name</th>
                    <th>Last name</th>
                    <th>Years of experience</th>
                  </tr>
                </thead>
                <tbody>
                  {% if redactor_list %}
                  {% for redactor in redactor_list %}
                  <tr>
                    <td>{{ redactor.id }}</td>
                    <td><a href="{{ redactor.get_absolute_url }}">{{ redactor.username }} {% if user == redactor %} (Me){% endif %}</a></td>
                    <td>{{ redactor.first_name }}</td>
                    <td>{{ redactor.last_name }}</td>
                    <td>{{ redactor.years_of_experience }}</td>
                  </tr>
                  {% endfor %}
                  {% else %}
                  <tr>
                    <td colspan="5" class="text-center">There are no redactors in the agency.</td>
                  </tr>
                  {% endif %}
                </tbody>
                {% block pagination %}
                    {% include 'includes/pagination.html' %}
                {% endblock %}
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/newspaper/topic_confirm_delete.html
{% extends "layouts/base.html" %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <h1>Delete topic?</h1>
        <p>Are you sure you want to delete the topic "{{ object.name }}"?</p>

        <form id="manufacturer-delete-form" action="" method="post">
          {% csrf_token %}
          <input type="submit" value="Yes" class="btn btn-danger">
          <a href="{% url 'newspaper:topic-list' %}" class="btn btn-secondary">Cancel</a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/newspaper/topic_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{{ object|yesno:"Update,Create" }} Topic</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="" method="post" novalidate>
          {% csrf_token %}
          {{ form|crispy }}

          <div class="d-flex justify-content-end">
            <input class="btn btn-primary" type="submit" value="Submit">
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/newspaper/topic_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<section class="pcoded-main-container">
    <div class="pcoded-content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Topic List</h5>
                        <form action="" method="get" class="form-inline">
                            {{ search_form|crispy }}
                              <input class="btn btn-secondary" type="submit" value="🔎" id="search-form">
                          </form>
                        <a style="float: right" href="{% url 'newspaper:topic-create' %}" class="btn btn-primary link-to-page">Create</a>
                    </div>
                    <div class="card-body table-border-style">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Name</th>
                                        <th>Update</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if topic_list %}
                                    {% for topic in topic_list %}
                                    <tr>
                                        <td>{{ topic.id }}</td>
                                        <td>{{ topic.name }}</td>
                                        <td>
                                          <a class="waves-effect waves-light btn-small blue" href="{% url 'newspaper:topic-update' pk=topic.id %}">
                                            Update
                                          </a>
                                        </td>
                                        <td>
                                          <a class="waves-effect waves-light btn-small red" href="{% url 'newspaper:topic-delete' pk=topic.id %}">
                                            Delete
                                          </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    {% else %}
                                    <tr>
                                        <td colspan="4">There are no topics</td>
                                    </tr>
                                    {% endif %}
                                </tbody>
                                {% block pagination %}
                                    {% include 'includes/pagination.html' %}
                                {% endblock %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}


<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}